services:
  - type: web
    name: horilla
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    startCommand: ./start.sh
    envVars:
      - key: DATABASE_URL
        value: postgresql://horilla_db_srmf_user:3i64DCLuCVYJM8Ceru5NcelQpwxKnzZK@dpg-d285gare5dus73f8b0j0-a/horilla_db_srmf
      - key: DJANGO_SETTINGS_MODULE
        value: horilla.settings
      - key: PORT
        value: 5432
      - key: ALLOWED_HOSTS
        value: targeticon-hrms-6p2l.onrender.com,localhost,127.0.0.1
      - key: CSRF_TRUSTED_ORIGINS
        value: https://targeticon-hrms-6p2l.onrender.com
